[package]
name = "ecoli"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]

[dependencies]
hmm = { git = "https://github.com/turnage/hmm.git" }

[dependencies.clap]
version = "2"
features = ["yaml"]
